name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: '0'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;29.0.14206865"
          echo "NDK_HOME=$ANDROID_HOME/ndk/29.0.14206865" >> $GITHUB_ENV
          sed -i '10i\        ndkVersion = "29.0.14206865"' ${{ github.workspace }}/V2rayNG/app/build.gradle.kts

      - name: Configure Direct Rules and Custom Routing Defaults
        run: |
          # Безопасная подмена констант маршрутизации в MmkvManager.kt
          FILE=$(find . -name "MmkvManager.kt" | head -n 1)
          if [ -n "$FILE" ]; then
            # Переключаем режим маршрутизации по умолчанию на "3" (Пользовательские правила)
            sed -i 's/ROUTING_MODE, "0"/ROUTING_MODE, "3"/g' $FILE
            sed -i 's/ROUTING_MODE, "2"/ROUTING_MODE, "3"/g' $FILE

            # Зашиваем твои домены напрямую в список исключений
            RU_RULES="geoip:ru,domain:ru,domain:su,domain:xn--p1ai,geosite:yandex,geosite:vk,domain:ozon.ru,domain:wildberries.ru,domain:wb.ru,domain:avito.ru,domain:sberbank.ru,domain:tinkoff.ru,domain:tbank.ru,domain:gosuslugi.ru"
            sed -i "s/ROUTING_DIRECT, \"\"/ROUTING_DIRECT, \"$RU_RULES\"/g" $FILE
          fi

      - name: Build libhevtun
        run: |
          bash compile-hevtun.sh

      - name: Copy libhevtun
        run: |
          cp -r ${{ github.workspace }}/libs ${{ github.workspace }}/V2rayNG/app

      - name: Fetch AndroidLibXrayLite tag
        run: |
          pushd AndroidLibXrayLite
          CURRENT_TAG=$(git describe --tags --abbrev=0)
          echo "CURRENT_TAG=$CURRENT_TAG" >> $GITHUB_ENV
          popd

      - name: Download libv2ray
        uses: robinraju/release-downloader@v1.13
        with:
          repository: '2dust/AndroidLibXrayLite'
          tag: ${{ env.CURRENT_TAG }}
          fileName: 'libv2ray.aar'
          out-file-path: 'V2rayNG/app/libs/'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Debug APK
        run: |
          cd ${{ github.workspace }}/V2rayNG
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          chmod 755 gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: quest-vpn-apk
          path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/**/*.apk
